name: Lint project

on:
    push:
      branches:
        - "main"
    pull_request:

permissions:
  contents: read
jobs:
  lint:
    name: Check for linting issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
      - name: Install dependencies
        run: |
            npm ci
      - name: Run the linter
        run: |
            npm run eslint-check
        continue-on-error: false