name: Lint project

on:
    push:
      branches:
        - "main"
    pull_request:

permissions:
  contents: read
jobs:
  lint:
    name: Check for linting issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
      - name: Install dependencies
        run: |
            npm ci
      - name: Run the linter
        run: |
            npm run eslint-check
        continue-on-error: false